import { Occupation } from "./types";
import { toUTC } from "./time";

const examples = [
  {
    n: 1,
    vehicle: 1,
    startDay: 0,
    startTime: "18:00",
    endDay: 0,
    endTime: "21:00",
    kind: "reservation",
    activity: "Traslado a encuentro vecinal",
    destination: "Centro comunitario",
    organization: "Junta vecinal de ejemplo",
    cancelled: false,
  },
  {
    n: 2,
    vehicle: 2,
    startDay: 0,
    startTime: "08:30",
    endDay: 0,
    endTime: "13:00",
    kind: "reservation",
    activity: "Atenciones de salud rural",
    destination: "Centro de salud",
    organization: "Programa de salud ficticio",
    cancelled: false,
  },
  {
    n: 3,
    vehicle: 3,
    startDay: 1,
    startTime: "07:30",
    endDay: 1,
    endTime: "17:30",
    kind: "reservation",
    activity: "Salida educativa",
    destination: "Museo regional",
    organization: "Escuela de ejemplo",
    cancelled: false,
  },
  {
    n: 4,
    vehicle: 1,
    startDay: 2,
    startTime: "09:00",
    endDay: 2,
    endTime: "19:00",
    kind: "reservation",
    activity: "Encuentro deportivo comunal",
    destination: "Estadio regional",
    organization: "Club deportivo ficticio",
    cancelled: false,
  },
  {
    n: 5,
    vehicle: 2,
    startDay: 3,
    startTime: "09:00",
    endDay: 3,
    endTime: "12:00",
    kind: "reservation",
    activity: "Traslado de personas mayores",
    destination: "Centro diurno",
    organization: "Club de mayores de ejemplo",
    cancelled: false,
  },
  {
    n: 6,
    vehicle: 2,
    startDay: 3,
    startTime: "12:00",
    endDay: 3,
    endTime: "16:00",
    kind: "reservation",
    activity: "Taller de participación ciudadana",
    destination: "Biblioteca comunal",
    organization: "Programa comunitario ficticio",
    cancelled: false,
  },
  {
    n: 7,
    vehicle: 4,
    startDay: 4,
    startTime: "08:00",
    endDay: 4,
    endTime: "14:00",
    kind: "reservation",
    activity: "Visita técnica a sectores rurales",
    destination: "Sector rural norte",
    organization: "Unidad municipal de ejemplo",
    cancelled: false,
  },
  {
    n: 8,
    vehicle: 1,
    startDay: 5,
    startTime: "08:00",
    endDay: 5,
    endTime: "18:00",
    kind: "reservation",
    activity: "Jornada cultural escolar",
    destination: "Teatro regional",
    organization: "Escuela de ejemplo",
    cancelled: false,
  },
  {
    n: 9,
    vehicle: 3,
    startDay: 6,
    startTime: "00:00",
    endDay: 8,
    endTime: "00:00",
    kind: "maintenance",
    activity: "Mantenimiento preventivo",
    destination: "Taller municipal",
    organization: "Unidad de flota ficticia",
    cancelled: false,
  },
  {
    n: 10,
    vehicle: 2,
    startDay: 6,
    startTime: "10:00",
    endDay: 6,
    endTime: "17:00",
    kind: "reservation",
    activity: "Operativo comunitario",
    destination: "Sede vecinal",
    organization: "Organización comunitaria ficticia",
    cancelled: false,
  },
  {
    n: 11,
    vehicle: 4,
    startDay: 7,
    startTime: "07:00",
    endDay: 7,
    endTime: "13:30",
    kind: "reservation",
    activity: "Traslado a controles médicos",
    destination: "Hospital regional",
    organization: "Programa de salud ficticio",
    cancelled: false,
  },
  {
    n: 12,
    vehicle: 1,
    startDay: 8,
    startTime: "08:00",
    endDay: 10,
    endTime: "20:00",
    kind: "reservation",
    activity: "Viaje cultural de varios días",
    destination: "Circuito regional",
    organization: "Agrupación cultural de ejemplo",
    cancelled: false,
  },
  {
    n: 13,
    vehicle: 3,
    startDay: 9,
    startTime: "09:00",
    endDay: 9,
    endTime: "16:00",
    kind: "reservation",
    activity: "Visita a feria de servicios",
    destination: "Plaza regional",
    organization: "Organización vecinal de ejemplo",
    cancelled: false,
  },
  {
    n: 14,
    vehicle: 2,
    startDay: 10,
    startTime: "00:00",
    endDay: 11,
    endTime: "00:00",
    kind: "reservation",
    activity: "Jornada comunitaria de día completo",
    destination: "Parque comunal",
    organization: "Programa comunitario ficticio",
    cancelled: false,
  },
  {
    n: 15,
    vehicle: 4,
    startDay: 11,
    startTime: "08:00",
    endDay: 11,
    endTime: "17:00",
    kind: "maintenance",
    activity: "Revisión de frenos y neumáticos",
    destination: "Taller municipal",
    organization: "Unidad de flota ficticia",
    cancelled: false,
  },
  {
    n: 16,
    vehicle: 1,
    startDay: 12,
    startTime: "08:30",
    endDay: 12,
    endTime: "18:30",
    kind: "reservation",
    activity: "Encuentro de personas mayores",
    destination: "Centro recreativo",
    organization: "Club de mayores de ejemplo",
    cancelled: false,
  },
  {
    n: 17,
    vehicle: 3,
    startDay: 13,
    startTime: "06:30",
    endDay: 13,
    endTime: "21:00",
    kind: "reservation",
    activity: "Competencia deportiva regional",
    destination: "Complejo deportivo",
    organization: "Club deportivo ficticio",
    cancelled: false,
  },
  {
    n: 18,
    vehicle: 2,
    startDay: 14,
    startTime: "09:00",
    endDay: 14,
    endTime: "13:00",
    kind: "reservation",
    activity: "Taller de educación ambiental",
    destination: "Centro ambiental",
    organization: "Escuela de ejemplo",
    cancelled: false,
  },
  {
    n: 19,
    vehicle: 4,
    startDay: 15,
    startTime: "08:00",
    endDay: 15,
    endTime: "14:00",
    kind: "reservation",
    activity: "Operativo rural de atención",
    destination: "Sector rural sur",
    organization: "Unidad municipal de ejemplo",
    cancelled: false,
  },
  {
    n: 20,
    vehicle: 1,
    startDay: 16,
    startTime: "00:00",
    endDay: 18,
    endTime: "00:00",
    kind: "maintenance",
    activity: "Mantención y revisión técnica",
    destination: "Taller municipal",
    organization: "Unidad de flota ficticia",
    cancelled: false,
  },
  {
    n: 21,
    vehicle: 3,
    startDay: 17,
    startTime: "09:00",
    endDay: 17,
    endTime: "18:00",
    kind: "reservation",
    activity: "Encuentro de organizaciones sociales",
    destination: "Centro comunitario",
    organization: "Agrupación social de ejemplo",
    cancelled: false,
  },
  {
    n: 22,
    vehicle: 2,
    startDay: 19,
    startTime: "08:00",
    endDay: 19,
    endTime: "15:00",
    kind: "reservation",
    activity: "Feria de emprendimiento local",
    destination: "Plaza comunal",
    organization: "Agrupación de emprendedores ficticia",
    cancelled: false,
  },
  {
    n: 23,
    vehicle: 4,
    startDay: 21,
    startTime: "08:00",
    endDay: 21,
    endTime: "18:00",
    kind: "reservation",
    activity: "Salida cultural comunitaria",
    destination: "Museo regional",
    organization: "Junta vecinal de ejemplo",
    cancelled: false,
  },
  {
    n: 24,
    vehicle: 1,
    startDay: 23,
    startTime: "07:00",
    endDay: 24,
    endTime: "19:00",
    kind: "reservation",
    activity: "Participación en festival regional",
    destination: "Recinto cultural",
    organization: "Agrupación cultural de ejemplo",
    cancelled: false,
  },
  {
    n: 25,
    vehicle: 3,
    startDay: 25,
    startTime: "09:00",
    endDay: 25,
    endTime: "17:00",
    kind: "reservation",
    activity: "Actividad recreativa familiar",
    destination: "Parque regional",
    organization: "Programa comunitario ficticio",
    cancelled: false,
  },
  {
    n: 26,
    vehicle: 2,
    startDay: 27,
    startTime: "08:30",
    endDay: 27,
    endTime: "13:30",
    kind: "reservation",
    activity: "Traslado a atenciones de salud",
    destination: "Centro de salud",
    organization: "Programa de salud ficticio",
    cancelled: false,
  },
  {
    n: 27,
    vehicle: 3,
    startDay: 1,
    startTime: "08:00",
    endDay: 1,
    endTime: "15:00",
    kind: "reservation",
    activity: "Salida educativa cancelada",
    destination: "Museo regional",
    organization: "Escuela de ejemplo",
    cancelled: true,
  },
] as const;

export function demoUsage(today: string): Occupation[] {
  const month = today.slice(0, 7);
  const at = (day: number, time: string) =>
    toUTC(`${month}-${String(day + 1).padStart(2, "0")}T${time}`);
  return examples.map((event) => ({
    id: `demo-usage-${event.n}`,
    vehicle_id: `demo-${event.vehicle}`,
    kind: event.kind,
    starts_at: at(event.startDay, event.startTime),
    ends_at: at(event.endDay, event.endTime),
    activity: event.activity,
    destination: event.destination,
    organization: event.organization,
    responsible: `Responsable ficticio ${event.n}`,
    contact: "Contacto de demostración, sin datos reales",
    notes: "Dato ficticio para explorar el calendario.",
    cancelled: event.cancelled,
  }));
}
